# Generated by Django 5.2.7 on 2025-10-28 10:42

import django.db.models.deletion
import django.utils.timezone
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome do projeto')),
                ('slug', models.SlugField(editable=False, max_length=140, unique=True)),
                ('methodology', models.CharField(choices=[('scrum', 'Scrum'), ('kanban', 'Kanban'), ('xp', 'Extreme Programming (XP)')], default='scrum', max_length=20, verbose_name='Metodologia')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, help_text='Opcional. PNG/JPG/WebP para identificar rapidamente.', null=True, upload_to=projects.models.project_image_upload_to, verbose_name='Imagem do projeto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Gerente do projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
