# Generated by Django 5.2.8 on 2025-11-06 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('key', models.SlugField(help_text='Short slug used in URLs and integrations', max_length=64, unique=True)),
                ('methodology', models.CharField(choices=[('scrum', 'Scrum'), ('kanban', 'Kanban'), ('xp', 'Extreme Programming (XP)')], default='scrum', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('repo_owner', models.CharField(help_text='User or organization that will own the repo in Gitea', max_length=120)),
                ('repo_name', models.CharField(blank=True, help_text='Repository name in Gitea (defaults to project name)', max_length=120)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=12)),
                ('default_branch', models.CharField(default='main', max_length=64)),
                ('auto_init', models.BooleanField(default=True, help_text='Create initial README in the repo')),
                ('gitea_repo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint_length_days', models.PositiveIntegerField(default=14, help_text='Sprint length (Scrum)')),
                ('wip_limit', models.PositiveIntegerField(default=3, help_text='Default WIP per column (Kanban)')),
                ('xp_pair_programming', models.BooleanField(default=True, help_text='Prefer pair programming (XP)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('developer', 'Developer'), ('reporter', 'Reporter'), ('guest', 'Guest')], default='developer', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
