# Generated by Django 5.2.8 on 2025-11-26 16:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('senior', 'Senior'), ('regular', 'Regular'), ('junior', 'Junior')], db_index=True, default='regular', help_text='Controls allowed actions inside the system.', max_length=20)),
                ('gitea_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='User ID in Gitea', null=True)),
                ('gitea_avatar_url', models.URLField(blank=True, null=True)),
                ('gitea_url', models.URLField(blank=True, help_text='Gitea base URL used for automatic sync', null=True)),
                ('password_updated_at', models.DateTimeField(blank=True, null=True)),
                ('gitea_max_repo_creation', models.IntegerField(blank=True, help_text='Max number of repos user can create (None = server default)', null=True)),
                ('gitea_visibility', models.CharField(blank=True, choices=[('public', 'public'), ('limited', 'limited'), ('private', 'private')], help_text='Gitea profile visibility', max_length=16, null=True)),
                ('gitea_allow_create_organization', models.BooleanField(default=False)),
                ('gitea_allow_git_hook', models.BooleanField(default=False)),
                ('gitea_allow_import_local', models.BooleanField(default=False)),
                ('gitea_restricted', models.BooleanField(default=False)),
                ('gitea_prohibit_login', models.BooleanField(default=False)),
                ('gitea_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gitea_website', models.URLField(blank=True, null=True)),
                ('gitea_location', models.CharField(blank=True, max_length=255, null=True)),
                ('gitea_description', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='One-time token for password setup', max_length=72, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If defined, tokens beyond this point are invalid.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
