# Generated by Django 5.2.8 on 2025-11-26 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(default='#6b4ce6', help_text='CSS hex (#RRGGBB ou #RRGGBBAA)', max_length=9)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_label_name')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('key', models.SlugField(help_text='Short key (unique per project)', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('review', 'In review'), ('verified', 'Verified'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('gitea_fork_owner', models.CharField(blank=True, max_length=120)),
                ('gitea_fork_name', models.CharField(blank=True, max_length=120)),
                ('gitea_fork_url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Responsável atual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='tasck.label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('reporter', models.ForeignKey(help_text='Quem criou/relatou a task', on_delete=django.db.models.deletion.PROTECT, related_name='reported_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(db_index=True, max_length=64)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('author_email', models.CharField(blank=True, max_length=160)),
                ('committed_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('html_url', models.URLField(blank=True)),
                ('code_quality_text', models.TextField(blank=True)),
                ('resolution_text', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False, help_text='Se este commit já foi processado por IA.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='tasck.task')),
            ],
            options={
                'ordering': ['-committed_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('developer', 'Developer'), ('reporter', 'Reporter'), ('guest', 'Guest')], default='developer', max_length=16)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tasck.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('user', 'User'), ('gitea', 'Gitea'), ('system', 'System')], default='user', max_length=16)),
                ('author_name', models.CharField(blank=True, help_text='Nome livre do autor', max_length=120)),
                ('text', models.TextField()),
                ('payload', models.JSONField(blank=True, help_text='Metadata opcional (ex.: resposta da API do Gitea)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasck.task')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasck_task_project_26b906_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'priority'], name='tasck_task_project_7e4da0_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='uniq_task_project_key'),
        ),
        migrations.AddIndex(
            model_name='taskcommit',
            index=models.Index(fields=['task', 'sha'], name='tasck_taskc_task_id_f634bb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcommit',
            index=models.Index(fields=['task', 'committed_date'], name='tasck_taskc_task_id_2b0d01_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcommit',
            constraint=models.UniqueConstraint(fields=('task', 'sha'), name='uniq_task_commit_sha'),
        ),
        migrations.AddConstraint(
            model_name='taskmember',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='uniq_task_member'),
        ),
        migrations.AddIndex(
            model_name='taskmessage',
            index=models.Index(fields=['task', 'created_at'], name='tasck_taskm_task_id_eeedef_idx'),
        ),
    ]
