# Generated by Django 5.2.8 on 2025-12-01 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(max_length=120)),
                ('repo_name', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('main', 'Main branch'), ('fork', 'User fork'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('sha', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True)),
                ('html_url', models.URLField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('author_email', models.CharField(blank=True, max_length=160)),
                ('committed_date', models.DateTimeField(blank=True, null=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False, help_text='Se este commit já foi processado pela IA.')),
                ('ai_score', models.IntegerField(blank=True, help_text='Nota da IA (0–10) para qualidade do código.', null=True)),
                ('code_quality_text', models.TextField(blank=True, help_text='Comentário da IA sobre a qualidade do código.')),
                ('resolution_text', models.TextField(blank=True, help_text='Descrição de como este commit ajuda a resolver a task.')),
                ('ai_payload', models.JSONField(blank=True, help_text='Metadados / resposta bruta da IA.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text="Commits rastreados pelo app 'commits' (IA, métricas, etc).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_commits', to='tasck.task')),
            ],
            options={
                'ordering': ['-committed_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MainBranchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Resumo em linguagem natural do estado atual do projeto.')),
                ('chunks', models.JSONField(blank=True, help_text='Chunks usados no RAG (se houver).', null=True)),
                ('vector_store_id', models.CharField(blank=True, help_text='ID da collection no vector-store externo, se usar.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Snapshot atual ativo do projeto.')),
                ('commit', models.OneToOneField(help_text='Commit HEAD da main quando este snapshot foi gerado.', on_delete=django.db.models.deletion.CASCADE, related_name='main_snapshot', to='commits.commit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('repo_owner', 'repo_name', 'sha'), name='uniq_commit_repo_sha'),
        ),
        migrations.AddConstraint(
            model_name='mainbranchsnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'commit'), name='uniq_main_snapshot_project_commit'),
        ),
    ]
